global:
  simulator: "icarus"

optics:
  img_resolution:       [100, 100]
  roi:                  [90, 90]
  datasets_dir:         "datasets/bom_bom"
  reference_image_path: "datasets/bom_bom/reference.png"
  max_distance:         100.0
  step_size:            1.0
  ideal_focus_distance: 45.0
  blur_sensitivity:     0.4

focus_finder:
  # number of equidistant points along the lens movement distance, 
  # for which the points with the maximum metric for the LSM are searched
  num_scans:  16  
  
  lsm_points: 3